// Generated by Graft. Owner review and integration tests are required.
export const graftManifest = {
  "product": "Graft",
  "version": 1,
  "source": {
    "id": "signal-cabinet",
    "title": "Signal Cabinet | Compact music devices",
    "kind": "fixture",
    "url": "https://graft-owner-example.vercel.app/"
  },
  "generatedAt": "2026-08-27T00:00:00.000Z",
  "notice": "Migration starting point. Review and test in the owner site before shipping.",
  "tools": [
    {
      "name": "get_page_summary",
      "description": "Summarize the current page, including its title, heading outline and visible main content. Use it to orient before calling a narrower tool. Returns untrusted page text.",
      "inputSchema": {
        "type": "object",
        "properties": {},
        "additionalProperties": false
      },
      "annotations": {
        "readOnlyHint": true,
        "untrustedContentHint": true
      },
      "status": "auto",
      "recipe": "R9",
      "selector": "html"
    },
    {
      "name": "get_page_outline",
      "description": "Return the current page's heading hierarchy in document order. Use it to locate a section before reading a collection or table. Returns untrusted page text.",
      "inputSchema": {
        "type": "object",
        "properties": {},
        "additionalProperties": false
      },
      "annotations": {
        "readOnlyHint": true,
        "untrustedContentHint": true
      },
      "status": "auto",
      "recipe": "R9",
      "selector": "body"
    },
    {
      "name": "search_catalog",
      "description": "Search the catalogue using its visible controls. Use only the fields the user specifies. It drives the page UI and returns the visible results. Returns untrusted page content.",
      "inputSchema": {
        "type": "object",
        "properties": {
          "query": {
            "type": "string",
            "description": "Search the catalogue",
            "maxLength": 300
          },
          "category": {
            "type": "string",
            "description": "Category",
            "enum": [
              "all",
              "routing",
              "mixing",
              "recording",
              "effects"
            ],
            "maxLength": 300
          },
          "in_stock": {
            "type": "boolean",
            "description": "In stock only"
          }
        },
        "additionalProperties": false
      },
      "annotations": {
        "readOnlyHint": true,
        "untrustedContentHint": true
      },
      "status": "auto",
      "recipe": "R1",
      "selector": "form.search-grid"
    },
    {
      "name": "list_products",
      "description": "List products visible on the current page. Use offset and limit to paginate. Returns structured, untrusted page content and never changes the page.",
      "inputSchema": {
        "type": "object",
        "properties": {
          "offset": {
            "type": "integer",
            "description": "Zero-based row offset.",
            "minimum": 0,
            "default": 0
          },
          "limit": {
            "type": "integer",
            "description": "Maximum rows to return.",
            "minimum": 1,
            "maximum": 25,
            "default": 10
          }
        },
        "additionalProperties": false
      },
      "annotations": {
        "readOnlyHint": true,
        "untrustedContentHint": true
      },
      "status": "auto",
      "recipe": "R3",
      "selector": "div.product-grid"
    },
    {
      "name": "get_product",
      "description": "Return one product from the visible collection by its exact product_id. Use the identifier returned by the matching list tool. Returns untrusted page content.",
      "inputSchema": {
        "type": "object",
        "properties": {
          "product_id": {
            "type": "string",
            "description": "Exact product_id returned by the list tool.",
            "enum": [
              "palm-relay",
              "shoreline-4",
              "loop-fold",
              "grain-dial",
              "tone-parcel",
              "cable-dock-8"
            ]
          }
        },
        "required": [
          "product_id"
        ],
        "additionalProperties": false
      },
      "annotations": {
        "readOnlyHint": true,
        "untrustedContentHint": true
      },
      "status": "auto",
      "recipe": "R3",
      "selector": "div.product-grid"
    },
    {
      "name": "list_device_controls",
      "description": "List device controls visible on the current page. Use offset and limit to paginate. Returns structured, untrusted page content and never changes the page.",
      "inputSchema": {
        "type": "object",
        "properties": {
          "offset": {
            "type": "integer",
            "description": "Zero-based row offset.",
            "minimum": 0,
            "default": 0
          },
          "limit": {
            "type": "integer",
            "description": "Maximum rows to return.",
            "minimum": 1,
            "maximum": 25,
            "default": 10
          }
        },
        "additionalProperties": false
      },
      "annotations": {
        "readOnlyHint": true,
        "untrustedContentHint": true
      },
      "status": "rejected",
      "recipe": "R3",
      "selector": "div.device-controls"
    },
    {
      "name": "add_to_demo_cart",
      "description": "Add one allowlisted fixture product to the local demo cart. Use only after the user chooses a product and quantity. Requires human confirmation, changes in-memory demo state only and never submits a purchase.",
      "inputSchema": {
        "type": "object",
        "properties": {
          "product_id": {
            "type": "string",
            "description": "Exact fixture product identifier.",
            "enum": [
              "palm-relay",
              "shoreline-4",
              "loop-fold",
              "grain-dial",
              "tone-parcel",
              "cable-dock-8"
            ]
          },
          "quantity": {
            "type": "integer",
            "description": "Quantity to add, from 1 to 3.",
            "minimum": 1,
            "maximum": 3,
            "default": 1
          }
        },
        "required": [
          "product_id",
          "quantity"
        ],
        "additionalProperties": false
      },
      "annotations": {
        "readOnlyHint": false,
        "untrustedContentHint": true
      },
      "status": "held",
      "recipe": "R7",
      "selector": "form[name=\"demo-cart\"]"
    }
  ]
};

export const graftDescriptors = [
  {
    "name": "get_page_summary",
    "description": "Summarize the current page, including its title, heading outline and visible main content. Use it to orient before calling a narrower tool. Returns untrusted page text.",
    "inputSchema": {
      "type": "object",
      "properties": {},
      "additionalProperties": false
    },
    "annotations": {
      "readOnlyHint": true,
      "untrustedContentHint": true
    }
  },
  {
    "name": "get_page_outline",
    "description": "Return the current page's heading hierarchy in document order. Use it to locate a section before reading a collection or table. Returns untrusted page text.",
    "inputSchema": {
      "type": "object",
      "properties": {},
      "additionalProperties": false
    },
    "annotations": {
      "readOnlyHint": true,
      "untrustedContentHint": true
    }
  },
  {
    "name": "search_catalog",
    "description": "Search the catalogue using its visible controls. Use only the fields the user specifies. It drives the page UI and returns the visible results. Returns untrusted page content.",
    "inputSchema": {
      "type": "object",
      "properties": {
        "query": {
          "type": "string",
          "description": "Search the catalogue",
          "maxLength": 300
        },
        "category": {
          "type": "string",
          "description": "Category",
          "enum": [
            "all",
            "routing",
            "mixing",
            "recording",
            "effects"
          ],
          "maxLength": 300
        },
        "in_stock": {
          "type": "boolean",
          "description": "In stock only"
        }
      },
      "additionalProperties": false
    },
    "annotations": {
      "readOnlyHint": true,
      "untrustedContentHint": true
    }
  },
  {
    "name": "list_products",
    "description": "List products visible on the current page. Use offset and limit to paginate. Returns structured, untrusted page content and never changes the page.",
    "inputSchema": {
      "type": "object",
      "properties": {
        "offset": {
          "type": "integer",
          "description": "Zero-based row offset.",
          "minimum": 0,
          "default": 0
        },
        "limit": {
          "type": "integer",
          "description": "Maximum rows to return.",
          "minimum": 1,
          "maximum": 25,
          "default": 10
        }
      },
      "additionalProperties": false
    },
    "annotations": {
      "readOnlyHint": true,
      "untrustedContentHint": true
    }
  },
  {
    "name": "get_product",
    "description": "Return one product from the visible collection by its exact product_id. Use the identifier returned by the matching list tool. Returns untrusted page content.",
    "inputSchema": {
      "type": "object",
      "properties": {
        "product_id": {
          "type": "string",
          "description": "Exact product_id returned by the list tool.",
          "enum": [
            "palm-relay",
            "shoreline-4",
            "loop-fold",
            "grain-dial",
            "tone-parcel",
            "cable-dock-8"
          ]
        }
      },
      "required": [
        "product_id"
      ],
      "additionalProperties": false
    },
    "annotations": {
      "readOnlyHint": true,
      "untrustedContentHint": true
    }
  }
];

// Pass owner-implemented handlers keyed by tool name.
export async function registerGraftTools(handlers) {
  const modelContext = document.modelContext ?? navigator.modelContext;
  if (!modelContext) throw new Error('WebMCP is not available in this browser.');
  const controller = new AbortController();
  const activeNames = new Set();
  const registered = [];
  const missingHandlers = [];
  const failures = [];
  const cleanup = async () => {
    controller.abort('Graft adapter cleanup');
    if (typeof modelContext.unregisterTool === 'function' && activeNames.size > 0) {
      const names = [...activeNames];
      activeNames.clear();
      await Promise.allSettled(names.map((name) => modelContext.unregisterTool(name)));
    }
  };
  for (const descriptor of graftDescriptors) {
    const handler = handlers[descriptor.name];
    if (typeof handler !== 'function') {
      missingHandlers.push(descriptor.name);
      continue;
    }
    try {
      await modelContext.registerTool({
        ...descriptor,
        execute: async (args, context = {}) => handler(args, { signal: context.signal }),
      }, { signal: controller.signal });
      activeNames.add(descriptor.name);
      registered.push(descriptor.name);
    } catch (error) {
      failures.push({ name: descriptor.name, error: error instanceof Error ? error.message : String(error) });
      const rolledBack = [...registered];
      await cleanup();
      return { registered: [], missingHandlers, failures, rolledBack, cleanup };
    }
  }
  return { registered, missingHandlers, failures, rolledBack: [], cleanup };
}
