import type {
  JsonSchema,
  ModelContextToolAnnotations,
  ToolExecutionContext,
  ToolExecutionResult,
} from "./lib";
import { validateToolArguments } from "./lib/validation";

export interface GraftExportDescriptor {
  name: string;
  description: string;
  inputSchema: JsonSchema;
  annotations?: ModelContextToolAnnotations;
}

export type GraftExportHandler = (
  args: Record<string, unknown>,
  context: ToolExecutionContext,
) => ToolExecutionResult | Promise<ToolExecutionResult>;

export interface GraftExportModelContext {
  registerTool: (
    descriptor: GraftExportDescriptor & {
      execute: GraftExportHandler;
    },
    options?: { signal?: AbortSignal },
  ) => void | Promise<void>;
  unregisterTool?: (name: string) => void | Promise<void>;
}

export interface GraftAdapterRegistrationReport {
  registered: string[];
  missingHandlers: string[];
  failures: Array<{ name: string; error: string }>;
  rolledBack: string[];
  cleanup: () => Promise<void>;
}

function errorMessage(error: unknown): string {
  return error instanceof Error ? error.message : String(error);
}

export async function registerExportedTools(
  modelContext: GraftExportModelContext,
  descriptors: readonly GraftExportDescriptor[],
  handlers: Readonly<Record<string, GraftExportHandler | undefined>>,
): Promise<GraftAdapterRegistrationReport> {
  const controller = new AbortController();
  const activeNames = new Set<string>();
  const registered: string[] = [];
  const missingHandlers: string[] = [];
  const failures: Array<{ name: string; error: string }> = [];

  const cleanup = async (): Promise<void> => {
    controller.abort("Graft adapter cleanup");
    if (modelContext.unregisterTool && activeNames.size > 0) {
      const names = [...activeNames];
      activeNames.clear();
      await Promise.allSettled(
        names.map((name) => modelContext.unregisterTool?.(name)),
      );
    }
  };

  for (const descriptor of descriptors) {
    const handler = handlers[descriptor.name];
    if (typeof handler !== "function") {
      missingHandlers.push(descriptor.name);
      continue;
    }

    try {
      await modelContext.registerTool(
        {
          ...descriptor,
          execute: async (args, context = {}) => {
            validateToolArguments(descriptor, args);
            return handler(args, { signal: context.signal });
          },
        },
        { signal: controller.signal },
      );
      activeNames.add(descriptor.name);
      registered.push(descriptor.name);
    } catch (error) {
      failures.push({ name: descriptor.name, error: errorMessage(error) });
      const rolledBack = [...registered];
      await cleanup();
      return {
        registered: [],
        missingHandlers,
        failures,
        rolledBack,
        cleanup,
      };
    }
  }

  return {
    registered,
    missingHandlers,
    failures,
    rolledBack: [],
    cleanup,
  };
}

export interface GraftExportTool extends GraftExportDescriptor {
  /** Recipe and selector let the inlined runtime drive the page unaided. */
  recipe?: string;
  selector?: string;
  action?: string;
  destructive?: boolean;
}

/**
 * Emits a self-contained adapter. The runtime is inlined rather than fetched so
 * a site that ships this never takes a runtime dependency on Graft's host.
 */
export function buildAdapterModule(
  manifest: unknown,
  tools: readonly GraftExportTool[],
  runtimeSource: string,
): string {
  const names = tools.map((tool) => tool.name);
  const localEffects = tools
    .filter((tool) => tool.annotations?.readOnlyHint === false && !tool.destructive)
    .map((tool) => tool.name);
  const consequential = tools.filter((tool) => tool.destructive).map((tool) => tool.name);

  return [
    "// Generated by Graft. Review before shipping.",
    "//",
    "// Add this to your page and the tools below register themselves:",
    "//",
    '//   <script type="module">',
    '//     import { registerGraftTools } from "./graft-adapter.js";',
    "//     await registerGraftTools();",
    "//   </script>",
    "//",
    `// Tools: ${names.join(", ") || "(none)"}`,
    localEffects.length
      ? `// Local page effects: ${localEffects.join(", ")}. These may move or reveal the current page.`
      : consequential.length
        ? "// No exported tool changes the local viewport."
        : "// Every automatically exported tool is read-only.",
    consequential.length
      ? `// Consequential tools: ${consequential.join(", ")}. Pass { confirm } to enable them.`
      : "// No exported tool performs a consequential mutation.",
    "//",
    "// Graft compiled the recipe and selector for each tool, so the bundled",
    "// runtime drives your live DOM without hand-written handlers. To take over",
    "// any single tool, pass your own:",
    "//",
    "//   await registerGraftTools({ handlers: { list_products: async (args) => ... } });",
    "",
    "/* ---- Graft runtime, inlined. No network calls, no dependency on Graft. ---- */",
    runtimeSource.trim(),
    "/* ---- end runtime ---- */",
    "",
    `export const graftManifest = ${JSON.stringify(manifest, null, 2)};`,
    "",
    `export const graftTools = ${JSON.stringify(tools, null, 2)};`,
    "",
    "function graftOwn(object, key) {",
    "  return Object.prototype.hasOwnProperty.call(object, key);",
    "}",
    "",
    "function graftValueType(value) {",
    "  if (value === null) return 'null';",
    "  if (Array.isArray(value)) return 'array';",
    "  if (typeof value === 'number' && Number.isInteger(value)) return 'integer';",
    "  return typeof value;",
    "}",
    "",
    "function graftMatchesType(schema, value) {",
    "  switch (schema.type) {",
    "    case undefined: return true;",
    "    case 'null': return value === null;",
    "    case 'array': return Array.isArray(value);",
    "    case 'object': return value !== null && typeof value === 'object' && !Array.isArray(value);",
    "    case 'integer': return typeof value === 'number' && Number.isFinite(value) && Number.isInteger(value);",
    "    case 'number': return typeof value === 'number' && Number.isFinite(value);",
    "    default: return typeof value === schema.type;",
    "  }",
    "}",
    "",
    "function graftValidateValue(schema, value, path, issues) {",
    "  if (!graftMatchesType(schema, value)) {",
    "    issues.push({",
    "      path,",
    "      code: 'wrong_type',",
    "      message: `${path} must be ${schema.type ?? 'a valid value'}, received ${graftValueType(value)}`,",
    "    });",
    "    return;",
    "  }",
    "  if (schema.enum && !schema.enum.some((candidate) => Object.is(candidate, value))) {",
    "    issues.push({",
    "      path,",
    "      code: 'invalid_enum',",
    "      message: `${path} must be one of ${schema.enum.map((item) => JSON.stringify(item)).join(', ')}`,",
    "    });",
    "  }",
    "  if (typeof value === 'string') {",
    "    if (schema.minLength !== undefined && value.length < schema.minLength) {",
    "      issues.push({",
    "        path,",
    "        code: 'min_length',",
    "        message: `${path} must contain at least ${schema.minLength} characters`,",
    "      });",
    "    }",
    "    if (schema.maxLength !== undefined && value.length > schema.maxLength) {",
    "      issues.push({",
    "        path,",
    "        code: 'max_length',",
    "        message: `${path} must contain at most ${schema.maxLength} characters`,",
    "      });",
    "    }",
    "    if (schema.pattern !== undefined) {",
    "      try {",
    "        if (!new RegExp(schema.pattern).test(value)) {",
    "          issues.push({",
    "            path,",
    "            code: 'invalid_pattern',",
    "            message: `${path} must match pattern ${JSON.stringify(schema.pattern)}`,",
    "          });",
    "        }",
    "      } catch {",
    "        issues.push({",
    "          path,",
    "          code: 'invalid_pattern',",
    "          message: `${path} cannot be checked because its schema pattern is invalid`,",
    "        });",
    "      }",
    "    }",
    "  }",
    "  if (typeof value === 'number') {",
    "    if (schema.minimum !== undefined && value < schema.minimum) {",
    "      issues.push({",
    "        path,",
    "        code: 'minimum',",
    "        message: `${path} must be at least ${schema.minimum}`,",
    "      });",
    "    }",
    "    if (schema.maximum !== undefined && value > schema.maximum) {",
    "      issues.push({",
    "        path,",
    "        code: 'maximum',",
    "        message: `${path} must be at most ${schema.maximum}`,",
    "      });",
    "    }",
    "  }",
    "  if (Array.isArray(value) && schema.items) {",
    "    value.forEach((item, index) => graftValidateValue(schema.items, item, `${path}[${index}]`, issues));",
    "  }",
    "  if (value !== null && typeof value === 'object' && !Array.isArray(value)) {",
    "    graftValidateObject(schema, value, path, issues);",
    "  }",
    "}",
    "",
    "function graftValidateObject(schema, value, path, issues) {",
    "  const properties = schema.properties ?? {};",
    "  for (const required of schema.required ?? []) {",
    "    if (!graftOwn(value, required) || value[required] === undefined) {",
    "      issues.push({",
    "        path: `${path}.${required}`,",
    "        code: 'missing_required',",
    "        message: `${path}.${required} is required`,",
    "      });",
    "    }",
    "  }",
    "  for (const [key, item] of Object.entries(value)) {",
    "    const childPath = `${path}.${key}`;",
    "    const propertySchema = graftOwn(properties, key) ? properties[key] : undefined;",
    "    if (propertySchema) {",
    "      graftValidateValue(propertySchema, item, childPath, issues);",
    "      continue;",
    "    }",
    "    if (schema.additionalProperties === false) {",
    "      issues.push({",
    "        path: childPath,",
    "        code: 'additional_property',",
    "        message: `${childPath} is not allowed`,",
    "      });",
    "      continue;",
    "    }",
    "    if (schema.additionalProperties && typeof schema.additionalProperties === 'object') {",
    "      graftValidateValue(schema.additionalProperties, item, childPath, issues);",
    "    }",
    "  }",
    "}",
    "",
    "class GraftToolArgumentValidationError extends Error {",
    "  constructor(toolName, issues) {",
    "    super(`Invalid arguments for “${toolName}”: ${issues.map((issue) => issue.message).join('; ')}`);",
    "    this.name = 'ToolArgumentValidationError';",
    "    this.issues = issues;",
    "  }",
    "}",
    "",
    "function validateGraftToolArguments(tool, args) {",
    "  const issues = [];",
    "  graftValidateValue(tool.inputSchema, args, '$', issues);",
    "  if (issues.length > 0) {",
    "    throw new GraftToolArgumentValidationError(tool.name, issues);",
    "  }",
    "}",
    "",
    "function graftCancelledResult(message = 'Cancelled: the user did not confirm.') {",
    "  return {",
    "    content: [{ type: 'text', text: message }],",
    "    structuredContent: { ok: false, message },",
    "    isError: true,",
    "  };",
    "}",
    "",
    "function graftAbortError(signal) {",
    "  if (signal?.reason instanceof Error) return signal.reason;",
    "  if (signal?.reason !== undefined) return new Error(String(signal.reason));",
    "  return new DOMException('The operation was aborted.', 'AbortError');",
    "}",
    "",
    "function graftThrowIfAborted(signal) {",
    "  if (signal?.aborted) throw graftAbortError(signal);",
    "}",
    "",
    "function graftWithAbort(value, signal) {",
    "  if (!signal) return value;",
    "  graftThrowIfAborted(signal);",
    "  return new Promise((resolve, reject) => {",
    "    const onAbort = () => reject(graftAbortError(signal));",
    "    signal.addEventListener('abort', onAbort, { once: true });",
    "    value.then(",
    "      (result) => { signal.removeEventListener('abort', onAbort); resolve(result); },",
    "      (error) => { signal.removeEventListener('abort', onAbort); reject(error); },",
    "    );",
    "  });",
    "}",
    "",
    "async function graftConfirmOverride(tool, args, context, confirm) {",
    "  if (!tool.destructive) return null;",
    "  if (typeof confirm !== 'function') {",
    "    return graftCancelledResult('Blocked: this tool requires explicit in-page confirmation.');",
    "  }",
    "  const confirmed = await graftWithAbort(",
    "    Promise.resolve(confirm({ tool, args, target: null, signal: context.signal })),",
    "    context.signal,",
    "  );",
    "  graftThrowIfAborted(context.signal);",
    "  return confirmed ? null : graftCancelledResult();",
    "}",
    "",
    "export async function registerGraftTools(options = {}) {",
    "  const modelContext = document.modelContext ?? navigator.modelContext;",
    "  if (!modelContext) throw new Error('WebMCP is not available in this browser.');",
    "  const { handlers: overrides = {}, ...runtimeOptions } = options;",
    "  const generated = GraftRuntime.createGraftHandlers(graftTools, runtimeOptions);",
    "  const handlers = { ...generated, ...overrides };",
    "  const controller = new AbortController();",
    "  const activeNames = new Set();",
    "  const registered = [];",
    "  const missingHandlers = [];",
    "  const failures = [];",
    "  const cleanup = async () => {",
    "    controller.abort('Graft adapter cleanup');",
    "    if (typeof modelContext.unregisterTool === 'function' && activeNames.size > 0) {",
    "      const names = [...activeNames];",
    "      activeNames.clear();",
    "      await Promise.allSettled(names.map((name) => modelContext.unregisterTool(name)));",
    "    }",
    "  };",
    "  for (const tool of graftTools) {",
    "    const handler = handlers[tool.name];",
    "    const ownerOverride = graftOwn(overrides, tool.name) && typeof overrides[tool.name] === 'function';",
    "    if (typeof handler !== 'function') {",
    "      missingHandlers.push(tool.name);",
    "      continue;",
    "    }",
    "    try {",
    "      await modelContext.registerTool({",
    "        name: tool.name,",
    "        description: tool.description,",
    "        inputSchema: tool.inputSchema,",
    "        annotations: tool.annotations,",
    "        execute: async (args = {}, context = {}) => {",
    "          validateGraftToolArguments(tool, args);",
    "          if (ownerOverride) {",
    "            const cancelled = await graftConfirmOverride(tool, args, context, runtimeOptions.confirm);",
    "            if (cancelled) return cancelled;",
    "          }",
    "          return handler(args, { signal: context.signal });",
    "        },",
    "      }, { signal: controller.signal });",
    "      activeNames.add(tool.name);",
    "      registered.push(tool.name);",
    "    } catch (error) {",
    "      failures.push({ name: tool.name, error: error instanceof Error ? error.message : String(error) });",
    "      const rolledBack = [...registered];",
    "      await cleanup();",
    "      return { registered: [], missingHandlers, failures, rolledBack, cleanup };",
    "    }",
    "  }",
    "  return { registered, missingHandlers, failures, rolledBack: [], cleanup };",
    "}",
    "",
  ].join("\n");
}
