import type {
  JsonSchema,
  ModelContextToolAnnotations,
  ToolExecutionContext,
  ToolExecutionResult,
} from "./lib";

export interface GraftExportDescriptor {
  name: string;
  description: string;
  inputSchema: JsonSchema;
  annotations?: ModelContextToolAnnotations;
}

export type GraftExportHandler = (
  args: Record<string, unknown>,
  context: ToolExecutionContext,
) => ToolExecutionResult | Promise<ToolExecutionResult>;

export interface GraftExportModelContext {
  registerTool: (
    descriptor: GraftExportDescriptor & {
      execute: GraftExportHandler;
    },
    options?: { signal?: AbortSignal },
  ) => void | Promise<void>;
  unregisterTool?: (name: string) => void | Promise<void>;
}

export interface GraftAdapterRegistrationReport {
  registered: string[];
  missingHandlers: string[];
  failures: Array<{ name: string; error: string }>;
  rolledBack: string[];
  cleanup: () => Promise<void>;
}

function errorMessage(error: unknown): string {
  return error instanceof Error ? error.message : String(error);
}

export async function registerExportedTools(
  modelContext: GraftExportModelContext,
  descriptors: readonly GraftExportDescriptor[],
  handlers: Readonly<Record<string, GraftExportHandler | undefined>>,
): Promise<GraftAdapterRegistrationReport> {
  const controller = new AbortController();
  const activeNames = new Set<string>();
  const registered: string[] = [];
  const missingHandlers: string[] = [];
  const failures: Array<{ name: string; error: string }> = [];

  const cleanup = async (): Promise<void> => {
    controller.abort("Graft adapter cleanup");
    if (modelContext.unregisterTool && activeNames.size > 0) {
      const names = [...activeNames];
      activeNames.clear();
      await Promise.allSettled(
        names.map((name) => modelContext.unregisterTool?.(name)),
      );
    }
  };

  for (const descriptor of descriptors) {
    const handler = handlers[descriptor.name];
    if (typeof handler !== "function") {
      missingHandlers.push(descriptor.name);
      continue;
    }

    try {
      await modelContext.registerTool(
        {
          ...descriptor,
          execute: async (args, context = {}) =>
            handler(args, { signal: context.signal }),
        },
        { signal: controller.signal },
      );
      activeNames.add(descriptor.name);
      registered.push(descriptor.name);
    } catch (error) {
      failures.push({ name: descriptor.name, error: errorMessage(error) });
      const rolledBack = [...registered];
      await cleanup();
      return {
        registered: [],
        missingHandlers,
        failures,
        rolledBack,
        cleanup,
      };
    }
  }

  return {
    registered,
    missingHandlers,
    failures,
    rolledBack: [],
    cleanup,
  };
}

export interface GraftExportTool extends GraftExportDescriptor {
  /** Recipe and selector let the inlined runtime drive the page unaided. */
  recipe?: string;
  selector?: string;
  action?: string;
  destructive?: boolean;
}

/**
 * Emits a self-contained adapter. The runtime is inlined rather than fetched so
 * a site that ships this never takes a runtime dependency on Graft's host.
 */
export function buildAdapterModule(
  manifest: unknown,
  tools: readonly GraftExportTool[],
  runtimeSource: string,
): string {
  const names = tools.map((tool) => tool.name);
  const localEffects = tools
    .filter((tool) => tool.annotations?.readOnlyHint === false && !tool.destructive)
    .map((tool) => tool.name);
  const consequential = tools.filter((tool) => tool.destructive).map((tool) => tool.name);

  return [
    "// Generated by Graft. Review before shipping.",
    "//",
    "// Add this to your page and the tools below register themselves:",
    "//",
    '//   <script type="module">',
    '//     import { registerGraftTools } from "./graft-adapter.js";',
    "//     await registerGraftTools();",
    "//   </script>",
    "//",
    `// Tools: ${names.join(", ") || "(none)"}`,
    localEffects.length
      ? `// Local page effects: ${localEffects.join(", ")}. These may move or reveal the current page.`
      : consequential.length
        ? "// No exported tool changes the local viewport."
        : "// Every automatically exported tool is read-only.",
    consequential.length
      ? `// Consequential tools: ${consequential.join(", ")}. Pass { confirm } to enable them.`
      : "// No exported tool performs a consequential mutation.",
    "//",
    "// Graft compiled the recipe and selector for each tool, so the bundled",
    "// runtime drives your live DOM without hand-written handlers. To take over",
    "// any single tool, pass your own:",
    "//",
    "//   await registerGraftTools({ handlers: { list_products: async (args) => ... } });",
    "",
    "/* ---- Graft runtime, inlined. No network calls, no dependency on Graft. ---- */",
    runtimeSource.trim(),
    "/* ---- end runtime ---- */",
    "",
    `export const graftManifest = ${JSON.stringify(manifest, null, 2)};`,
    "",
    `export const graftTools = ${JSON.stringify(tools, null, 2)};`,
    "",
    "export async function registerGraftTools(options = {}) {",
    "  const modelContext = document.modelContext ?? navigator.modelContext;",
    "  if (!modelContext) throw new Error('WebMCP is not available in this browser.');",
    "  const { handlers: overrides = {}, ...runtimeOptions } = options;",
    "  const generated = GraftRuntime.createGraftHandlers(graftTools, runtimeOptions);",
    "  const handlers = { ...generated, ...overrides };",
    "  const controller = new AbortController();",
    "  const activeNames = new Set();",
    "  const registered = [];",
    "  const missingHandlers = [];",
    "  const failures = [];",
    "  const cleanup = async () => {",
    "    controller.abort('Graft adapter cleanup');",
    "    if (typeof modelContext.unregisterTool === 'function' && activeNames.size > 0) {",
    "      const names = [...activeNames];",
    "      activeNames.clear();",
    "      await Promise.allSettled(names.map((name) => modelContext.unregisterTool(name)));",
    "    }",
    "  };",
    "  for (const tool of graftTools) {",
    "    const handler = handlers[tool.name];",
    "    if (typeof handler !== 'function') {",
    "      missingHandlers.push(tool.name);",
    "      continue;",
    "    }",
    "    try {",
    "      await modelContext.registerTool({",
    "        name: tool.name,",
    "        description: tool.description,",
    "        inputSchema: tool.inputSchema,",
    "        annotations: tool.annotations,",
    "        execute: async (args, context = {}) => handler(args, { signal: context.signal }),",
    "      }, { signal: controller.signal });",
    "      activeNames.add(tool.name);",
    "      registered.push(tool.name);",
    "    } catch (error) {",
    "      failures.push({ name: tool.name, error: error instanceof Error ? error.message : String(error) });",
    "      const rolledBack = [...registered];",
    "      await cleanup();",
    "      return { registered: [], missingHandlers, failures, rolledBack, cleanup };",
    "    }",
    "  }",
    "  return { registered, missingHandlers, failures, rolledBack: [], cleanup };",
    "}",
    "",
  ].join("\n");
}
